#!/usr/bin/bash

. /bin/tls-common.sh

. /bin/ironic-common.sh

wait_for_interface_or_ip

export IRONIC_PROXY_PORT=${IRONIC_PROXY_PORT:-6386}
export IRONIC_UPSTREAM_IP=${IRONIC_UPSTREAM_IP:-$IRONIC_IP}
export IRONIC_UPSTREAM_PORT=${IRONIC_UPSTREAM_PORT:-6385}
export IRONIC_UPSTREAM_PROTO=${IRONIC_UPSTREAM_PROTO:-$IRONIC_SCHEME}

if [[ "$IRONIC_UPSTREAM_IP" =~ .*:.* ]]; then
    export IRONIC_UPSTREAM_IP="[$IRONIC_UPSTREAM_IP]"
fi

if [[ -f "${HTTPD_CONF_DIR}/httpd.conf" ]]; then
    mv "${HTTPD_CONF_DIR}/httpd.conf" "${HTTPD_CONF_DIR}/httpd.conf.example"
fi

# Render the core httpd config
render_j2_config "/etc/httpd/conf/httpd-ironic-proxy.conf.j2" \
    "${HTTPD_CONF_DIR}/httpd.conf"

render_j2_config /etc/httpd-proxy.conf.j2 "${HTTPD_CONF_DIR_D}/ironic-proxy.conf"

exec /usr/sbin/httpd -DFOREGROUND -f "${HTTPD_CONF_DIR}/httpd.conf"
